import java.io.IOException;
import java.io.StringWriter;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.StringJoiner;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

/**
 * Writes the one document a service serves, src/main/resources/api/openapi.yaml, from the sources
 * sources.json beside it names: a path in the repository, or owner/repo@commit:path fetched from
 * that repository at that commit. Paths, components and tags are the union of the sources, a path
 * defined twice is an error, the info block is the first source's with every description joined and
 * the title sources.json may set. Vendored from guestgraph/service-conventions and run by
 * service-conventions/regen-api; the committed file is held against a fresh run in CI.
 */
public final class RegenApi {

  static final Path API = Path.of("src/main/resources/api");
  static final Path OUT = API.resolve("openapi.yaml");
  static final String HEADER =
      "# GENERATED by service-conventions/regen-api from src/main/resources/api/sources.json\n"
          + "# Do not edit by hand — CI fails on drift. Regenerate: sh service-conventions/regen-api\n";

  private RegenApi() {}

  public static void main(String[] args) throws IOException, InterruptedException {
    Yaml yaml = new Yaml();
    Map<String, Object> sources = yaml.load(Files.readString(API.resolve("sources.json")));
    List<?> list = sources.get("sources") instanceof List<?> l ? l : List.of();
    if (list.isEmpty()) {
      throw new IllegalStateException("sources.json names no sources");
    }
    List<Map<String, Object>> documents = new ArrayList<>();
    for (Object source : list) {
      documents.add(yaml.load(read(String.valueOf(source))));
    }
    Map<String, Object> merged = merge(documents, sources.get("title"));
    DumperOptions options = new DumperOptions();
    options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
    options.setIndent(2);
    options.setWidth(100);
    options.setPrettyFlow(true);
    StringWriter out = new StringWriter();
    new Yaml(options).dump(merged, out);
    Files.writeString(OUT, HEADER + out, StandardCharsets.UTF_8);
    System.out.println("wrote " + OUT + " from " + list.size() + " source(s)");
  }

  static String read(String source) throws IOException, InterruptedException {
    int at = source.indexOf('@');
    int colon = source.indexOf(':', at);
    if (at > 0 && colon > at) {
      String repo = source.substring(0, at);
      String commit = source.substring(at + 1, colon);
      String path = source.substring(colon + 1);
      URI uri = URI.create("https://raw.githubusercontent.com/" + repo + "/" + commit + "/" + path);
      HttpResponse<String> response =
          HttpClient.newHttpClient()
              .send(
                  HttpRequest.newBuilder(uri).GET().build(), HttpResponse.BodyHandlers.ofString());
      if (response.statusCode() != 200) {
        throw new IllegalStateException(uri + " answered " + response.statusCode());
      }
      return response.body();
    }
    return Files.readString(Path.of(source));
  }

  @SuppressWarnings("unchecked")
  static Map<String, Object> merge(List<Map<String, Object>> documents, Object title) {
    Map<String, Object> merged = new LinkedHashMap<>(documents.getFirst());
    Map<String, Object> info = new LinkedHashMap<>(section(merged, "info"));
    if (title != null) {
      info.put("title", title);
    }
    merged.put("info", info);
    Map<String, Object> paths = new LinkedHashMap<>();
    Map<String, Object> components = new LinkedHashMap<>();
    StringJoiner description = new StringJoiner("\n\n");
    List<Object> tags = new ArrayList<>();
    Set<Object> tagNames = new LinkedHashSet<>();
    for (Map<String, Object> document : documents) {
      Map<String, Object> documentInfo = section(document, "info");
      if (documentInfo.get("description") instanceof String text) {
        description.add(text.strip());
      }
      if (documentInfo.get("version") != null) {
        info.put("version", documentInfo.get("version"));
      }
      if (document.get("tags") instanceof List<?> documentTags) {
        for (Object tag : documentTags) {
          if (tag instanceof Map<?, ?> tagMap && tagNames.add(tagMap.get("name"))) {
            tags.add(tag);
          }
        }
      }
      section(document, "paths")
          .forEach(
              (path, item) -> {
                if (paths.putIfAbsent(path, item) != null) {
                  throw new IllegalStateException("The sources define path " + path + " twice");
                }
              });
      section(document, "components")
          .forEach(
              (kind, entries) -> {
                Map<String, Object> target =
                    (Map<String, Object>)
                        components.computeIfAbsent(kind, k -> new LinkedHashMap<String, Object>());
                if (entries instanceof Map<?, ?> entryMap) {
                  entryMap.forEach((name, schema) -> target.putIfAbsent((String) name, schema));
                }
              });
    }
    if (description.length() > 0) {
      info.put("description", description.toString());
    }
    if (!tags.isEmpty()) {
      merged.put("tags", tags);
    }
    merged.put("paths", paths);
    if (!components.isEmpty()) {
      merged.put("components", components);
    }
    return merged;
  }

  @SuppressWarnings("unchecked")
  static Map<String, Object> section(Map<String, Object> document, String key) {
    return document.get(key) instanceof Map<?, ?> m ? (Map<String, Object>) m : Map.of();
  }
}
