package io.guestgraph.service;

import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import org.springframework.core.io.ClassPathResource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.yaml.snakeyaml.Yaml;

/**
 * Serves the service's contract at GET /api-docs: the one document under src/main/resources/api,
 * generated by service-conventions/regen-api from the sources named beside it. Outside any guard,
 * since the document carries no data. Vendored from guestgraph/service-conventions, never edited in
 * a service.
 */
@RestController
public class ApiDocsController {

  private final Map<String, Object> document;

  public ApiDocsController() {
    try (InputStream in = new ClassPathResource("api/openapi.yaml").getInputStream()) {
      this.document = new Yaml().load(in);
    } catch (IOException e) {
      throw new IllegalStateException("Cannot load api/openapi.yaml", e);
    }
  }

  @GetMapping(value = "/api-docs", produces = "application/json")
  public Map<String, Object> apiDocs() {
    return document;
  }
}
